-- MySQL Script generated by MySQL Workbench
-- Mon Mar 19 18:37:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema typist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema typist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `typist` DEFAULT CHARACTER SET utf8 ;
USE `typist` ;

-- -----------------------------------------------------
-- Table `typist`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`revision` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NULL,
  `create_at` TIMESTAMP(0) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_revision_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_revision_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `typist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`posts` (
  `id` INT NOT NULL,
  `revision_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `update_at` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_revision1_idx` (`revision_id` ASC),
  INDEX `fk_posts_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_posts_revision1`
    FOREIGN KEY (`revision_id`)
    REFERENCES `typist`.`revision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `typist`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`comments` (
  `id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `commenter_ip` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `typist`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
