-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 13:19:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema typist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema typist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `typist` DEFAULT CHARACTER SET utf8 ;
USE `typist` ;

-- -----------------------------------------------------
-- Table `typist`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`revisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`revisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  `user_id` INT NULL,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `revision_id` INT NOT NULL,
  `category_id` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `expand_content` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `typist`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `typist`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commenter_ip` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `post_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
